---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.21.3-bullseye

inputs:
  - name: dp-frontend-router
    path: dp-frontend-router

outputs:
  - name: build

run:
  path: dp-frontend-router/ci/scripts/build.sh
