---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.10.2

inputs:
  - name: dp-frontend-router
    path: go/src/github.com/ONSdigital/dp-frontend-router

outputs:
  - name: build

run:
  path: go/src/github.com/ONSdigital/dp-frontend-router/ci/scripts/build.sh
